apiVersion: v1
kind: Secret
metadata:
  name: github-example
  namespace: default
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/dsuaveniq/mcs-customer-example
  username: dsuaveniq
  password: 