crds:
  enabled: true
  keep: true

replicaCount: 1

resources:
  requests:
    cpu: 10m
    memory: 32Mi

# A comma-separated string with the host and port of the recursive nameservers cert-manager should query.
dns01RecursiveNameservers: "8.8.8.8:53,1.1.1.1:53"

# Forces cert-manager to use only the recursive nameservers for verification.
# Enabling this option could cause the DNS01 self check to take longer owing to caching performed by the recursive nameservers.
dns01RecursiveNameserversOnly: true
